aws_region           = "us-east-1"
eks_cluster_name     = "app-cluster"
eks_cluster_endpoint = "https://4E2E57E93AF9A2622E28F5A6371664AC.gr7.us-east-1.eks.amazonaws.com"
eks_cluster_ca_cert  = "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJUEtFTGNxQ1dBKzB3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBMU1ETXhNakF5TWpaYUZ3MHpOVEExTURFeE1qQTNNalphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURPTk1oNlJoTkl5ZlROaFMya3ZvblduNEMyNHRJbmlXS1l6dE5EKzI1SXZ6MWpqajZwODU5VmJ1YmcKY3oyZXFibGo5OGdablNXTWRBbGhEQmdBOTFtOHZYZWVNSVFrTWRjU3VSL3FTeXFzYXM0akRVcTY4aktuczViQwplQnNsRThOSFlacGcyaTRKdUdHQmtld1VxM3RyQjgwdzJMaGU4OHJHNXhDZVNLNWlCeUlLVDNHbDhXWG4zd1R5Cjg5TXRhblN6Vldhblc2eTNmZGN2VHU2WW9TSXR2UmREeVc4ejlRb3NGT3drdGNZc3pJSDk2WXA1UUFuMTB6VjUKM2tlVXk2b1lTcnpKbTVqTUZ2Y3RYUmRWQjVCY1dGOGtBRjVjazRORDF4c2RHaEtsYkVSdWxtS2FEM0E3SGlxdQpUWnF6S3l5N0NMMEpnZEVCei9mZ0xFbldTNW5sQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTSXpXQm1vZzJrZlF2T2l2U2lEUWVnOWNnM1dEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQzk5ZlZ3VlNjOAppMkM4ZXd5bUJBUVFDQWsyNTRKTkt4T2Y0ei9jV3NHWHRHWnlxK044eDNiYnRaUGd5NDB2bk5OUW85U0lCMGxBCjJORmJBOG83K3gwNGZpUXhEbVBCbGxaYk03VklPazhxTHFtT0ZrSWdnNkpVOTl4bG84WUdaRUpkYWRyTmgwaEYKRkJnVEExdllxRVh2VTkzMDlWUmNUYXYydGdsY1UxZG1UTmRtbGdDb2RseXR5V0V2V3pLcFkwejRuNTdPUUlWLwoxTUMwNUxpbFJ1QlZGMTBkcEJkeWZrdWdXYm5YdSt4WlRiWmpSYWtldVh0bkpmc1lvMFk2WXl0TFNCdDZXZkEwCkxFMmRkNDJoUEU3M2VWc3lOa2xJNEpGV1BHNjZ1dHJrOWVzUHY4aG1xaHFKRElQbzhMUVhieDVuWUR4M0Y3ZXoKVldTa1dJZnZHNkF4Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"

# Domínio Base
base_domain = "mixnarede.com.br"

# Referência ao Cert-Manager já instalado
cert_manager_letsencrypt_server = "prod"

# Keycloak
keycloak_namespace        = "keycloak"
keycloak_create_namespace = true
keycloak_chart_version    = "24.6.1"
keycloak_service_type     = "ClusterIP"
keycloak_enable_https     = true
keycloak_create_ingress   = true
keycloak_admin_username   = "admin"
keycloak_admin_password   = "admin"

# Recursos do Keycloak
keycloak_resources_requests_cpu    = "500m"
keycloak_resources_requests_memory = "1Gi"
keycloak_resources_limits_cpu      = "1000m"
keycloak_resources_limits_memory   = "2Gi"

# PostgreSQL Externo
keycloak_external_db_enabled  = true
keycloak_external_db_host     = "keycloak.c8966ow2w0q1.us-east-1.rds.amazonaws.com"
keycloak_external_db_port     = 5432
keycloak_external_db_database = "keycloak"
keycloak_external_db_username = "keycloak"
keycloak_external_db_password = "keycloak"
